### ISSUE TITLE
Move to cyclejs org?

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs-stream#1]
@erykpiast This utility might be important often, how about moving it to the github [cyclejs org](https://github.com/cyclejs)? I can make you a member of the org

**Comment by erykpiast** [comment]
Let's do it!

2015-08-09 19:18 GMT+02:00 André Staltz <notifications@github.com>:

**Comment by erykpiast** [comment]
When I tried to transfer repository ownership: "You don’t have admin rights to cyclejs".

Do I something wrong or I just have to be an admin?

**Comment by staltz** [comment]
Try again

**Comment by erykpiast** [comment]
Done!
